-- PESO Basud Job Fair Management - Supabase (PostgreSQL) schema
-- Ported from MySQL (database/basud_db.sql) for the Supabase migration.
-- Conventions:
--   AUTO_INCREMENT        -> GENERATED BY DEFAULT AS IDENTITY (allows explicit id on data import)
--   ENUM('a','b')         -> TEXT + CHECK constraint (Supabase-recommended, flexible to extend)
--   TINYINT(1)            -> BOOLEAN
--   TIMESTAMP             -> TIMESTAMPTZ
--   updated_at            -> maintained by set_updated_at() trigger
--
-- Apply via Supabase SQL editor, or automatically during test setup.

DROP TABLE IF EXISTS
  document_attachments,
  member_documents,
  member_skills,
  member_employment_information,
  member_educational_background,
  member_emergency_contacts,
  member_special_categories,
  member_pwd_information,
  member_willing_to_work,
  member_employment_eligibility,
  member_government_information,
  member_addresses,
  member_contact_information,
  member_personal_information,
  members,
  staff_accounts
CASCADE;

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- staff_accounts
-- ---------------------------------------------------------------------------

CREATE TABLE staff_accounts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name  VARCHAR(120) NOT NULL,
  role          TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('staff')),
  account_status TEXT NOT NULL DEFAULT 'Active' CHECK (account_status IN ('Active', 'Inactive')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_staff_accounts_email UNIQUE (email)
);

CREATE TRIGGER staff_accounts_set_updated_at
  BEFORE UPDATE ON staff_accounts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- members + child tables
-- ---------------------------------------------------------------------------

CREATE TABLE members (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER members_set_updated_at
  BEFORE UPDATE ON members
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE member_personal_information (
  member_id    BIGINT NOT NULL PRIMARY KEY,
  last_name    VARCHAR(100) NOT NULL,
  first_name   VARCHAR(100) NOT NULL,
  middle_name  VARCHAR(100) DEFAULT NULL,
  suffix       VARCHAR(20) DEFAULT NULL,
  sex          TEXT NOT NULL CHECK (sex IN ('M', 'F')),
  date_of_birth DATE DEFAULT NULL,
  place_of_birth VARCHAR(150) DEFAULT NULL,
  age          INTEGER DEFAULT NULL,
  civil_status TEXT NOT NULL CHECK (civil_status IN ('Single', 'Married', 'Widowed', 'Separated')),
  nationality  VARCHAR(100) DEFAULT NULL,
  religion     VARCHAR(100) DEFAULT NULL,
  CONSTRAINT fk_personal_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_personal_name ON member_personal_information (last_name, first_name);

CREATE TABLE member_contact_information (
  member_id       BIGINT NOT NULL PRIMARY KEY,
  mobile_number   VARCHAR(30) DEFAULT NULL,
  email_address   VARCHAR(150) DEFAULT NULL,
  facebook_profile VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_contact_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_contact_mobile ON member_contact_information (mobile_number);
CREATE INDEX idx_contact_email ON member_contact_information (email_address);

CREATE TABLE member_addresses (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id       BIGINT NOT NULL,
  address_type    TEXT NOT NULL CHECK (address_type IN ('current', 'permanent')),
  same_as_current BOOLEAN NOT NULL DEFAULT false,
  house_no_street VARCHAR(255) DEFAULT NULL,
  barangay        VARCHAR(150) DEFAULT NULL,
  municipality_city VARCHAR(150) DEFAULT NULL,
  province        VARCHAR(150) DEFAULT NULL,
  zip_code        VARCHAR(20) DEFAULT NULL,
  CONSTRAINT fk_address_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_member_address_type UNIQUE (member_id, address_type)
);

CREATE TABLE member_government_information (
  member_id               BIGINT NOT NULL PRIMARY KEY,
  philsys_national_id_number VARCHAR(50) DEFAULT NULL,
  sss_number              VARCHAR(50) DEFAULT NULL,
  philhealth_number       VARCHAR(50) DEFAULT NULL,
  pagibig_number          VARCHAR(50) DEFAULT NULL,
  tin_number              VARCHAR(50) DEFAULT NULL,
  passport_number         VARCHAR(50) DEFAULT NULL,
  CONSTRAINT fk_government_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_employment_eligibility (
  member_id          BIGINT NOT NULL PRIMARY KEY,
  legally_eligible   TEXT NOT NULL DEFAULT 'Yes' CHECK (legally_eligible IN ('Yes', 'No')),
  valid_government_id TEXT NOT NULL DEFAULT 'Yes' CHECK (valid_government_id IN ('Yes', 'No')),
  CONSTRAINT fk_eligibility_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_willing_to_work (
  member_id  BIGINT NOT NULL,
  work_scope TEXT NOT NULL CHECK (work_scope IN ('Within Municipality', 'Within Province', 'Anywhere in the Philippines', 'Overseas')),
  PRIMARY KEY (member_id, work_scope),
  CONSTRAINT fk_willing_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_pwd_information (
  member_id              BIGINT NOT NULL PRIMARY KEY,
  is_person_with_disability TEXT NOT NULL DEFAULT 'No' CHECK (is_person_with_disability IN ('Yes', 'No')),
  disability_type        VARCHAR(150) DEFAULT NULL,
  CONSTRAINT fk_pwd_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_special_categories (
  member_id     BIGINT NOT NULL,
  category_code TEXT NOT NULL CHECK (category_code IN ('4ps', 'indigenous_people', 'solo_parent', 'senior_citizen', 'returning_ofw')),
  PRIMARY KEY (member_id, category_code),
  CONSTRAINT fk_special_category_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_emergency_contacts (
  member_id      BIGINT NOT NULL PRIMARY KEY,
  full_name      VARCHAR(150) DEFAULT NULL,
  relationship   VARCHAR(100) DEFAULT NULL,
  contact_number VARCHAR(30) DEFAULT NULL,
  address        VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_emergency_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_educational_background (
  member_id                    BIGINT NOT NULL PRIMARY KEY,
  highest_educational_attainment VARCHAR(150) DEFAULT NULL,
  school_name                  VARCHAR(150) DEFAULT NULL,
  course_program               VARCHAR(150) DEFAULT NULL,
  year_graduated               VARCHAR(20) DEFAULT NULL,
  honors_awards                VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_education_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_employment_information (
  member_id          BIGINT NOT NULL PRIMARY KEY,
  employment_status  TEXT NOT NULL DEFAULT 'Employment' CHECK (employment_status IN ('Employment', 'Unemployed', 'Self-Employed', 'Student', 'Fresh Graduate')),
  desired_position   VARCHAR(150) DEFAULT NULL,
  preferred_industry VARCHAR(150) DEFAULT NULL,
  expected_salary    VARCHAR(50) DEFAULT NULL,
  years_of_experience VARCHAR(50) DEFAULT NULL,
  CONSTRAINT fk_employment_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_skills (
  member_id            BIGINT NOT NULL PRIMARY KEY,
  technical_skills     TEXT DEFAULT NULL,
  soft_skills          TEXT DEFAULT NULL,
  language_spoken      VARCHAR(255) DEFAULT NULL,
  computer_skills      VARCHAR(255) DEFAULT NULL,
  certifications_license VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_skills_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE member_documents (
  member_id               BIGINT NOT NULL PRIMARY KEY,
  resume_attached         BOOLEAN NOT NULL DEFAULT false,
  valid_id_attached       BOOLEAN NOT NULL DEFAULT false,
  certificate_attached    BOOLEAN NOT NULL DEFAULT false,
  other_documents_attached BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT fk_documents_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- Digital document attachments (files uploaded to Supabase Storage).
-- Physical submissions stay tracked by member_documents.*_attached booleans.
CREATE TABLE document_attachments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     BIGINT NOT NULL,
  document_type TEXT NOT NULL CHECK (document_type IN ('resume', 'valid_id', 'certificate', 'other')),
  file_name     VARCHAR(255) NOT NULL,
  storage_path  TEXT NOT NULL,
  mime_type     VARCHAR(120) NOT NULL,
  file_size     BIGINT NOT NULL,
  uploaded_by   VARCHAR(190) DEFAULT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_attachment_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_attachment_storage_path UNIQUE (storage_path)
);

CREATE INDEX idx_attachments_member ON document_attachments (member_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- The application connects as the postgres role (transaction pooler), which
-- BYPASSES row level security, so the app keeps working untouched. Anon and
-- authenticated roles get no policies at all, so direct Supabase API access
-- to these tables is denied by default. Service role also bypasses RLS.
-- ---------------------------------------------------------------------------

ALTER TABLE staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_personal_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_contact_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_government_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_employment_eligibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_willing_to_work ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_pwd_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_special_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_emergency_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_educational_background ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_employment_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_attachments ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Seed: PESO admin account. Password: pesoadmin121314
-- Regenerate hash if password changes:
--   node -e "console.log(require('bcryptjs').hashSync('pesoadmin121314', 10))"
-- ---------------------------------------------------------------------------

INSERT INTO staff_accounts (email, password_hash, display_name, role, account_status)
VALUES (
  'pesoadmin@gmail.com',
  '$2b$10$OUNgCiP39MMK/97LHxFrKeV5h94jdihDWeEV1WNyJcdl1mMGjT32e',
  'PESO Administrator',
  'staff',
  'Active'
)
ON CONFLICT (email) DO NOTHING;
