-- 002_document_attachments.sql
-- Digital document attachments (Supabase Storage), RLS hardening, storage bucket.
-- Idempotent; applies to the public schema on the live Supabase project.
-- Test runs apply the same DDL from database/schema.sql instead.

CREATE TABLE IF NOT EXISTS document_attachments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     BIGINT NOT NULL,
  document_type TEXT NOT NULL CHECK (document_type IN ('resume', 'valid_id', 'certificate', 'other')),
  file_name     VARCHAR(255) NOT NULL,
  storage_path  TEXT NOT NULL,
  mime_type     VARCHAR(120) NOT NULL,
  file_size     BIGINT NOT NULL,
  uploaded_by   VARCHAR(190) DEFAULT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_attachment_member
    FOREIGN KEY (member_id) REFERENCES members (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_attachment_storage_path UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_attachments_member ON document_attachments (member_id);

-- Row Level Security: the app connects as the postgres role (pooler), which
-- bypasses RLS, so application behavior is unchanged. Anonymous/authenticated
-- Supabase API roles get zero policies -> deny all direct table access.
ALTER TABLE staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_personal_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_contact_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_government_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_employment_eligibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_willing_to_work ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_pwd_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_special_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_emergency_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_educational_background ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_employment_information ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_attachments ENABLE ROW LEVEL SECURITY;

-- Private storage bucket (backend-only access via service role).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'member_documents',
  'member_documents',
  false,
  10485760,
  ARRAY[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/plain'
  ]
)
ON CONFLICT (id) DO NOTHING;
